/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as jobMarketPlaceSol from "./JobMarketPlace.sol";
export type { jobMarketPlaceSol };
export type { Lock } from "./Lock";
export type { UserProfile } from "./UserProfile";
export * as factories from "./factories";
export type { JobMarketplace } from "./JobMarketPlace.sol/JobMarketplace";
export { JobMarketplace__factory } from "./factories/JobMarketPlace.sol/JobMarketplace__factory";
export { Lock__factory } from "./factories/Lock__factory";
export { UserProfile__factory } from "./factories/UserProfile__factory";
