/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as jobMarketPlaceSol from "./JobMarketPlace.sol";
export { Lock__factory } from "./Lock__factory";
export { UserProfile__factory } from "./UserProfile__factory";
